version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgcli:
    image: dencold/pgcli
    depends_on:
      - postgres
    entrypoint: pgcli -h postgres -U username -d ny_taxi